"""initial schema

Revision ID: 10636aa1b671
Revises:
Create Date: 2026-10-03 20:40:03.746013

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10636aa1b671'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('video_input_key', sa.String(length=50), nullable=False),
    sa.Column('prompt_input_key', sa.String(length=50), nullable=False),
    sa.Column('extra_input', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_prompts_single_active', 'prompts', ['is_active'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.create_table('recording_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('clips_per_day', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('min_seconds', sa.Integer(), nullable=False),
    sa.Column('max_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('recorded', 'queued', 'processing', 'done', 'failed', name='clip_status', native_enum=False, length=20), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('model_input', sa.JSON(), nullable=True),
    sa.Column('provider_job_id', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('augmented_path', sa.String(length=500), nullable=True),
    sa.Column('playback_path', sa.String(length=500), nullable=True),
    sa.Column('playback_fps', sa.Float(), nullable=True),
    sa.Column('playback_frames', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_recorded_at'), 'clips', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('scheduled_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='schedule_status', native_enum=False, length=20), nullable=False),
    sa.Column('clip_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_recordings_plan_date'), 'scheduled_recordings', ['plan_date'], unique=False)
    op.create_index(op.f('ix_scheduled_recordings_scheduled_at'), 'scheduled_recordings', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_recordings_scheduled_at'), table_name='scheduled_recordings')
    op.drop_index(op.f('ix_scheduled_recordings_plan_date'), table_name='scheduled_recordings')
    op.drop_table('scheduled_recordings')
    op.drop_table('devices')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_index(op.f('ix_clips_recorded_at'), table_name='clips')
    op.drop_table('clips')
    op.drop_table('users')
    op.drop_table('recording_settings')
    op.drop_index('uq_prompts_single_active', table_name='prompts', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.drop_table('prompts')
    # ### end Alembic commands ###
