[platformio]
data_dir = display-data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    lovyan03/LovyanGFX @ ^1.2.31
    bodmer/TJpg_Decoder @ ^1.1.0
    paulstoffregen/XPT2046_Touchscreen
    bblanchon/ArduinoJson @ ^7.4.2